spring:
  application:
    name: "demo"
  profiles:
    active: dev
  # devtools 설정
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2
  # Datasource 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # Hibernate
  jpa:
    show-sql: true

server:
  compression:
    enabled: false
    mime-types:
  ssl:
    enabled: false
